Squashed commit of the following:
commit ca10c4f48ce40df47405a87f393618d40b10cfa1
Merge: 6a7b3f5855 01041728e7
Author: Skold177 <113406182+Skold177@users.noreply.github.com>
Date:   Thu Oct 23 19:31:13 2025 -0400

    Merge remote-tracking branch 'upstream/base' into base

commit 01041728e7e93afaca0bae365d5e25f0714e6a7a
Merge: 2c50e23e9d ee7a7a8ceb
Author: WinterSolstice8 <60417494+WinterSolstice8@users.noreply.github.com>
Date:   Thu Oct 23 14:21:48 2025 -0600

    Merge pull request #8490 from cocosolos/clang-tidy-fix

    Fix optional clang-tidy

commit ee7a7a8ceb8f1e5acb7d6eb980dfffbd87993daf
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Thu Oct 23 19:38:09 2025 +0000

    Fix optional clang-tidy

    Missed a renamed var.

commit 2c50e23e9d964c9584e2406e49f635f9be23fac5
Merge: b7da4a4b31 02b485db9e
Author: WinterSolstice8 <60417494+WinterSolstice8@users.noreply.github.com>
Date:   Thu Oct 23 12:58:53 2025 -0600

    Merge pull request #8489 from cocosolos/docker

    Fix issue with Docker image names

commit 02b485db9e176459a42d753242aff9bc1f0153a0
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Thu Oct 23 18:20:41 2025 +0000

    Fix issue with Docker image names

commit b7da4a4b3102b4fc67097f26ca0a0dc00de375fd
Merge: 73505ce7a3 4cd50a96ec
Author: WinterSolstice8 <60417494+WinterSolstice8@users.noreply.github.com>
Date:   Thu Oct 23 11:57:31 2025 -0600

    Merge pull request #8486 from cocosolos/docker

    Fix issue with docker tags and meshes

commit 4cd50a96ec2c77aad68a880a5b0e54bbf6ab4bce
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Thu Oct 23 17:31:54 2025 +0000

    Fix issue with docker tags and meshes

commit 73505ce7a308f924ecbda86aa1eeafe60e80652f
Merge: 5c9acb5acd 7034493888
Author: Zach Toogood <zrtoogood@gmail.com>
Date:   Thu Oct 23 18:05:00 2025 +0100

    Merge pull request #8332 from cocosolos/docker

    Docker + CI Updates

commit 7034493888764f1de0deb3e54869fa9cadad2aba
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Thu Oct 16 05:05:31 2025 +0000

    Retry certain CI jobs on failure

    Windows startup checks and potentially APT can be problematic.

commit e6a1aea14a11470da0bb8603a8cbbdc7e91c8780
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Fri Jun 27 23:39:13 2025 -0400

    Add local development compose file

commit 52f34322c7635e5d9a6b4d11a076e3ab13ee30c4
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Thu Jun 5 04:08:18 2025 -0400

    Update CI/CD

    Build cache on commits to base using proper cache keys.
    Use fresh cache during CI builds (big improvement to build times).
    Skip clang-tidy if no source changes during CI builds.
    Improve CI results using GitHub Actions summaries.
    Move CI test job into separate workflow.
    Combine Windows and Linux test workflows.

    Note:
    ccache cache isn't being extracted from Docker image, causing full
    rebuilds every time. Disable Docker build in CI workflows until we can
    fix this.

commit 216694275ba0d1ee215952cd52a12f5dafaa9542
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Thu Jun 5 04:03:48 2025 -0400

    Add Docker support

    Ubuntu and Alpine based images, with options for a GCC or Clang build.
    Caching optimized for local building.
    See docker/README.md for more info.

commit a52f0c26f997d426d35bda194a6cd658fbc4f318
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Tue Sep 9 16:50:35 2025 -0400

    Update fmt

    Fixes issue with newer clang version:
    fmt/format.h:4429:27: error: identifier '_a' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]

commit 7bed22671a1c652893e987bc847b8e5872d19b91
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Thu Jun 5 03:54:01 2025 -0400

    Embed debug information in Windows executables

    Using external debugging info causes issues with relative paths.

commit 187621a9dc31b0ba7a4d8bfb48e873d552dfbae4
Author: Corey Sotiropoulos <coco@solos.dev>
Date:   Wed Oct 1 00:51:32 2025 -0400

    Format Python files with Black formatter

commit 5c9acb5acd0f05f8ad2702f9bc981cbe4f8d5ffa
Merge: f376e116e8 dd4309900d
Author: WinterSolstice8 <60417494+WinterSolstice8@users.noreply.github.com>
Date:   Thu Oct 23 09:41:43 2025 -0600

    Merge pull request #8484 from sruon/s2c_mission

    S2C: MISSION

commit f376e116e80fd465e8c3de4943148a6484ff0ae3
Merge: 943bb0de10 47343903a8
Author: Xaver-DaRed <60053999+Xaver-DaRed@users.noreply.github.com>
Date:   Thu Oct 23 13:00:13 2025 +0200

    Merge pull request #8452 from CriticalXI/bastok_mission_fix

    [lua, sql] Bastok 9-2 Behavior Adjustments

commit dd4309900d57f30cc75d35d602118242b52e47a8
Author: sruon <sruon@users.noreply.github.com>
Date:   Thu Oct 23 00:15:38 2025 -0600

    GP_SERV_COMMAND_MISSION

    Co-Authored-By: atom0s <atom0s@users.noreply.github.com>

commit 47343903a83c86461235d4df04040e4d1a6a80c2
Author: Critical <48370698+CriticalXI@users.noreply.github.com>
Date:   Tue Oct 14 21:04:07 2025 -0600

    [lua, sql] Bastok 9-2 Behavior Adjustments